name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build STS2 Mod
        uses: qbyoffice/AOShiRo-STS2_Actions/STS2/build@main
        with:
          project-name: ${{ github.event.repository.name }}
