name: Release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release STS2 Mod
        uses: qbyoffice/qbyoffice_actions/sts2/release@main
        with:
          project-name: ${{ github.event.repository.name }}
